features:
  custom_errors:
    enabled: false
  slack:
    notifications:
      enabled: false
    invites:
      enabled: false
  twitter:
    hangout_notifications:
      enabled: false
    notifications:
      enabled: false
  welcome_email:
    enabled: false

hangouts:
  app_id: '10095526298'

privileged_users: "random@random.com"
