features:
  slack:
    notifications:
      enabled: false
    invites:
      enabled: false
  twitter:
    notifications:
      enabled: false

  email_registrations:
    enabled: true

mailer:
  delivery_method: 'test'

privileged_users: 'chesa@example.com, random@random.com'

agile_bot_url: https://agile-bot.herokuapp.com
