features:
  slack:
    notifications:
      enabled: false
    invites:
      enabled: false
  twitter:
    hangout_notifications:
      enabled: false
    notifications:
      enabled: true

  email_registrations:
    enabled: true

mailer:
  delivery_method: 'test'

privileged_users: 'chesa@example.com, random@random.com' 

hangouts:
  app_id: '10095526298'

agile_bot_url: https://agile-bot.herokuapp.com
